### ISSUE TITLE
棋譜履歴ページへのリンク作成

### ISSUE THREAD

**Issue by usatyo** [usatyo/spice-family#35]
ボタンとかリンクとかなんでもいいので /record に飛ぶようにしてほしいです

**Comment by toyoshin5** [comment]
今からこれをしますが、これはResult画面から今回の対局の棋譜が見れるってことでいいですか？それとも過去の対局の棋譜も見ますか？

**Comment by toyoshin5** [comment]
Done

**Comment by usatyo** [comment]
・過去の対局も見れるようにする部分はrecordページで行います

**Comment by toyoshin5** [comment]
さっきマージしたんですけど今のorigin/mainで/から/record、/resultから/recordの遷移が既に実装済みです。文言含めて修正点あったら教えてください

**Comment by usatyo** [comment]
後で確認します
